services:
  dev:
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
      - "3000:3000"
  prod:
    build:
      context: .
      dockerfile: main.dockerfile
    ports:
      - "3001:3000"